// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYDhjz27BqiddkSxt3tW9RLvrEjDgOKc',
    appId: '1:757294368294:android:63f65388924d272a5fc8e7',
    messagingSenderId: '757294368294',
    projectId: 'just-pixel-studio',
    storageBucket: 'just-pixel-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9jl-EcI_r8xznlOaQj3_qrGIyNy3zbLE',
    appId: '1:757294368294:ios:426ee2d123a6e3895fc8e7',
    messagingSenderId: '757294368294',
    projectId: 'just-pixel-studio',
    storageBucket: 'just-pixel-studio.firebasestorage.app',
    iosBundleId: 'com.justpixel.studio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9jl-EcI_r8xznlOaQj3_qrGIyNy3zbLE',
    appId: '1:757294368294:ios:426ee2d123a6e3895fc8e7',
    messagingSenderId: '757294368294',
    projectId: 'just-pixel-studio',
    storageBucket: 'just-pixel-studio.firebasestorage.app',
    iosBundleId: 'com.justpixel.studio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4BvMQuwrrN4Vx5VLyMl3FCBG7o2hB1bg',
    appId: '1:757294368294:web:b3597ade64205fdc5fc8e7',
    messagingSenderId: '757294368294',
    projectId: 'just-pixel-studio',
    authDomain: 'just-pixel-studio.firebaseapp.com',
    storageBucket: 'just-pixel-studio.firebasestorage.app',
  );
}
